
#!/bin/bash
set -o errexit

PARAM_1="${1}"
PARAM_2="${2}"

PROTOCOLO_DEFAULT="http"
HOST_DEFAULT="proxy.sefaz.sefnet:3128"
FILE_NAME_CONF_PROXY_DEFAULT="proxy_http.conf"
PASTA_CONF_PROXY_DEFAULT="/etc/apt"

HOST="${HOST:-$HOST_DEFAULT}"
USUARIO="${USUARIO:-$PARAM_1}"
SENHA="${SENHA:-$PARAM_2}"

PROTOCOLO="${PROTOCOLO:-$PROTOCOLO_DEFAULT}"
PASTA_CONF_PROXY="${PASTA_CONF_PROXY:-$PASTA_CONF_PROXY_DEFAULT}"
FILE_NAME_CONF_PROXY="${FILE_NAME_CONF_PROXY:-$FILE_NAME_CONF_PROXY_DEFAULT}"
FILE_CONF_PROXY="${FILE_CONF_PROXY:-$PASTA_CONF_PROXY/$FILE_NAME_CONF_PROXY}"

PROTOCOLO_PROXY="${PROTOCOLO_PROXY:-$PROTOCOLO}"

URL="${PROTOCOLO:+$PROTOCOLO://}"
URL="$URL$USUARIO"
URL="$URL${SENHA:+:$SENHA}"
( [ ! -z "${USUARIO// }${SENHA// }" ] ) && URL="$URL@"
URL="$URL$HOST"

echo "Acquire::$PROTOCOLO_PROXY::Proxy \"$URL;\"" > $FILE_CONF_PROXY